---
title: "Visualize Volcanoes Opening Book"
author: "Simon Dorfman"
date: "12/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
.main-container {
  max-width: 2560px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r, results = 'hide', warning = FALSE, message = FALSE, echo=FALSE}

## Install and Load R Libraries

# list of packages we need for this doc

required_package_names <- c("readr", "dplyr", "tidyr", "stringr", "visNetwork", "DT", "htmltools", "bsplus")

 

# Install packages not yet installed

installed_packages <- required_package_names %in% rownames(installed.packages())

if (any(installed_packages == FALSE)) {

  install.packages(required_package_names[!installed_packages])

}

 

# Load required packages

invisible(lapply(required_package_names, library, character.only = TRUE))
```

```{r, results = 'hide', warning = FALSE, message = FALSE, echo=FALSE}
nodes <- read_csv("data/nodes.csv")
edges <- read_csv("data/edges.csv")

#try shortening so the viz actually loads:
# nodes <- nodes %>% slice_head(n = 2000)
# edges <- edges %>% slice_head(n = 2000)
```

```{r echo=FALSE}
# nodes <- data.frame(id = 1:7, label = 1:7, title = 1:7 , group = 1:7)
# edges <- data.frame(from = c(2,2,2,2,3,3),
#  to = c(1,3,4,5,6,7))

visNetwork(nodes, edges, width = "100%") %>% 
  visEdges(arrows = "to") %>% 
  visHierarchicalLayout()  %>%# same as   visLayout(hierarchical = TRUE) 
# visNetwork(nodes, edges, width = "100%") %>% 
  visNodes(shape = "dot") %>%
  visLayout(randomSeed = 12) # to have always the same network   
```

